pip install keyboard
pip install requests
pip install keyboard
pip install os
pip install datetime
pip install webbrowser
pip install time
pip install socket
pip install platform
pip install subprocess
pip install re
pip install sys
pip install sysconfig
pip install ctypes
pip install random
pip install requests
pip install GPUtil
pip install pyautogui
pip install colorama
pip install psutil
pip install pyperclip
pip install pillow
